### ISSUE TITLE
Will it violate the requirement for anonymous submission if supplying a GitHub repo?

### ISSUE THREAD

**Issue by zengsn** [paperswithcode/releasing-research-code#4]
I got a comment of violation for anonymous submission, when I once supplied a GitHub repo along with my submission to another conference. Is it a problem for NeurIPS?

**Comment by rstojnic** [comment]
@zengsn I believe the official guidance is to submit an anonymized zip file of your repository together with the paper submission. And then, once the paper is accepted, you can attach the github repository.

**Comment by zengsn** [comment]
@rstojnic Thank you. I understand now. :)
